### ISSUE TITLE
Kymograph.py numpy.math depreciation warning

### ISSUE THREAD

**Issue by Tom-TBT** [ome/scripts#218]
Seen in a stderr log on my fresh dev server with numpy v1.26.4:

It comes from `omero/analysis_scripts/Kymograph.py`

DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`

**Comment by jburel** [comment]
See https://github.com/ome/omero-scripts/pull/219
